spring:
  application:
    name: portal-server
  thymeleaf:
    mode: LEGACYHTML5
server:
  contextPath: /portal
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    registerWithEureka: false
